import type { Buyer, Product, ProductCategory, Seller } from "@/lib/types";

export const categories: ProductCategory[] = [
  "Beauty & Skincare",
  "Food & Beverage",
  "Apparel",
  "Supplements",
  "Home Goods",
  "Pet Products",
  "Health & Wellness",
];

export const commonDocuments = [
  "Commercial invoice",
  "Packing list",
  "Certificate of origin",
];

const baseSellers: Seller[] = [
  {
    id: "pacific-naturals",
    name: "Pacific Naturals Co.",
    location: "Los Angeles, California",
    state: "California",
    businessType: "Brand Owner",
    yearFounded: 2014,
    yearsInBusiness: 12,
    categories: ["Beauty & Skincare", "Health & Wellness"],
    certifications: ["GMP", "Leaping Bunny", "USDA Organic"],
    exportCountries: ["South Korea", "Japan", "Singapore", "Canada"],
    exportExperience:
      "Ships skincare and wellness products to Asian distributors with bilingual export documentation.",
    monthlyCapacity: "180,000 units",
    responseTime: "Under 8 hours",
    paymentTerms: ["30% deposit / 70% before shipment", "Wire transfer", "Letter of credit"],
    incoterms: ["EXW", "FOB", "CIF", "DDP"],
    documentsAvailable: [...commonDocuments, "COA", "MSDS", "Organic certificate"],
    contactPerson: "Maya Chen",
    contactEmail: "exports@pacificnaturals.example",
    website: "pacificnaturals.example",
    languages: ["English", "Korean"],
    rating: 4.8,
    reviewCount: 46,
    verified: true,
    description:
      "California-based clean beauty and wellness brand with private label capacity for retailers and specialty importers.",
  },
  {
    id: "harbor-foods",
    name: "Harbor Foods Export",
    location: "Seattle, Washington",
    state: "Washington",
    businessType: "Distributor",
    yearFounded: 2008,
    yearsInBusiness: 18,
    categories: ["Food & Beverage"],
    certifications: ["FDA Registered", "SQF", "Kosher"],
    exportCountries: ["South Korea", "Taiwan", "United Arab Emirates"],
    exportExperience:
      "Experienced with temperature-controlled LCL and FCL food shipments from Seattle and Oakland.",
    monthlyCapacity: "22 containers",
    responseTime: "Under 12 hours",
    paymentTerms: ["Wire transfer", "Letter of credit", "Net 30 for approved buyers"],
    incoterms: ["FOB", "CIF", "DDP"],
    documentsAvailable: [...commonDocuments, "FDA registration", "COA", "Health certificate"],
    contactPerson: "Daniel Brooks",
    contactEmail: "trade@harborfoodsexport.example",
    website: "harborfoodsexport.example",
    languages: ["English"],
    rating: 4.7,
    reviewCount: 58,
    verified: true,
    description:
      "Export distributor focused on premium American snacks, beverages, sauces, and natural foods.",
  },
  {
    id: "atlas-apparel",
    name: "Atlas Apparel Supply",
    location: "Portland, Oregon",
    state: "Oregon",
    businessType: "Manufacturer",
    yearFounded: 2011,
    yearsInBusiness: 15,
    categories: ["Apparel"],
    certifications: ["OEKO-TEX", "WRAP", "B Corp"],
    exportCountries: ["South Korea", "Mexico", "Australia"],
    exportExperience:
      "Supports custom sizing, hang tags, and export carton labeling for fashion retailers.",
    monthlyCapacity: "95,000 garments",
    responseTime: "1 business day",
    paymentTerms: ["50% deposit / 50% before shipment", "Wire transfer"],
    incoterms: ["EXW", "FOB"],
    documentsAvailable: [...commonDocuments, "Fabric composition sheet", "Test reports"],
    contactPerson: "Olivia Bennett",
    contactEmail: "global@atlasapparel.example",
    website: "atlasapparel.example",
    languages: ["English", "Spanish"],
    rating: 4.6,
    reviewCount: 33,
    verified: true,
    description:
      "Sustainable apparel manufacturer producing basics, athleisure, and private label seasonal capsules.",
  },
  {
    id: "summit-nutrition",
    name: "Summit Nutrition Labs",
    location: "Salt Lake City, Utah",
    state: "Utah",
    businessType: "Manufacturer",
    yearFounded: 2002,
    yearsInBusiness: 24,
    categories: ["Supplements", "Health & Wellness"],
    certifications: ["GMP", "NSF", "FDA Registered"],
    exportCountries: ["South Korea", "Thailand", "Vietnam", "Germany"],
    exportExperience:
      "Regular supplement exports with batch COA, stability data, and ingredient disclosure support.",
    monthlyCapacity: "2.4 million capsules",
    responseTime: "Under 6 hours",
    paymentTerms: ["Wire transfer", "Letter of credit", "Escrow available"],
    incoterms: ["EXW", "FOB", "CIF"],
    documentsAvailable: [...commonDocuments, "COA", "MSDS", "FDA registration"],
    contactPerson: "Ethan Miller",
    contactEmail: "sales@summitnutrition.example",
    website: "summitnutrition.example",
    languages: ["English"],
    rating: 4.9,
    reviewCount: 71,
    verified: true,
    description:
      "Contract manufacturer and brand owner for capsules, gummies, powders, and functional wellness blends.",
  },
  {
    id: "hearth-home",
    name: "Hearth & Home Goods",
    location: "Austin, Texas",
    state: "Texas",
    businessType: "Brand Owner",
    yearFounded: 2017,
    yearsInBusiness: 9,
    categories: ["Home Goods"],
    certifications: ["FSC", "Prop 65 Tested"],
    exportCountries: ["South Korea", "Japan", "New Zealand"],
    exportExperience:
      "Ships design-forward home goods with retail packaging and carton drop-test reports.",
    monthlyCapacity: "70,000 units",
    responseTime: "Under 10 hours",
    paymentTerms: ["30% deposit / 70% before shipment", "Wire transfer"],
    incoterms: ["EXW", "FOB", "DDP"],
    documentsAvailable: [...commonDocuments, "Material safety sheet", "Test reports"],
    contactPerson: "Grace Wilson",
    contactEmail: "wholesale@hearthhome.example",
    website: "hearthhome.example",
    languages: ["English"],
    rating: 4.5,
    reviewCount: 28,
    verified: true,
    description:
      "Modern home goods brand specializing in storage, kitchen, tabletop, and small-space organization.",
  },
  {
    id: "bright-paws",
    name: "Bright Paws Collective",
    location: "Denver, Colorado",
    state: "Colorado",
    businessType: "Wholesaler",
    yearFounded: 2015,
    yearsInBusiness: 11,
    categories: ["Pet Products"],
    certifications: ["FDA Registered", "AAFCO Compliant", "USDA Organic"],
    exportCountries: ["South Korea", "Hong Kong", "Philippines"],
    exportExperience:
      "Exports pet treats, grooming, and accessories with ingredient and label review support.",
    monthlyCapacity: "420,000 packs",
    responseTime: "Under 8 hours",
    paymentTerms: ["Wire transfer", "Letter of credit"],
    incoterms: ["FOB", "CIF", "DDP"],
    documentsAvailable: [...commonDocuments, "COA", "Health certificate", "Ingredient statement"],
    contactPerson: "Noah Parker",
    contactEmail: "export@brightpaws.example",
    website: "brightpaws.example",
    languages: ["English"],
    rating: 4.8,
    reviewCount: 39,
    verified: true,
    description:
      "Premium pet product wholesaler with Korean-market-friendly packaging formats and clean ingredient positioning.",
  },
  {
    id: "blue-ridge-wellness",
    name: "Blue Ridge Wellness",
    location: "Asheville, North Carolina",
    state: "North Carolina",
    businessType: "Brand Owner",
    yearFounded: 2013,
    yearsInBusiness: 13,
    categories: ["Health & Wellness", "Beauty & Skincare"],
    certifications: ["USDA Organic", "GMP", "Cruelty Free"],
    exportCountries: ["South Korea", "United Kingdom", "Singapore"],
    exportExperience:
      "Supports natural wellness buyers with compliant claims review and export documentation.",
    monthlyCapacity: "130,000 units",
    responseTime: "1 business day",
    paymentTerms: ["Wire transfer", "Credit card for samples"],
    incoterms: ["EXW", "FOB"],
    documentsAvailable: [...commonDocuments, "COA", "Organic certificate"],
    contactPerson: "Sarah Kim",
    contactEmail: "partners@blueridgewellness.example",
    website: "blueridgewellness.example",
    languages: ["English", "Korean"],
    rating: 4.7,
    reviewCount: 25,
    verified: true,
    description:
      "Natural wellness company offering aromatherapy, personal care, and herbal products for specialty retail.",
  },
  {
    id: "frontier-gourmet",
    name: "Frontier Gourmet Group",
    location: "Chicago, Illinois",
    state: "Illinois",
    businessType: "Wholesaler",
    yearFounded: 1999,
    yearsInBusiness: 27,
    categories: ["Food & Beverage"],
    certifications: ["FDA Registered", "SQF", "Non-GMO Project"],
    exportCountries: ["South Korea", "Malaysia", "Chile"],
    exportExperience:
      "Multi-brand food exporter with consolidated pallet programs for U.S. importers.",
    monthlyCapacity: "35 containers",
    responseTime: "Under 12 hours",
    paymentTerms: ["Wire transfer", "Letter of credit"],
    incoterms: ["FOB", "CIF"],
    documentsAvailable: [...commonDocuments, "FDA registration", "COA"],
    contactPerson: "Marcus Reed",
    contactEmail: "exports@frontiergourmet.example",
    website: "frontiergourmet.example",
    languages: ["English"],
    rating: 4.4,
    reviewCount: 64,
    verified: false,
    description:
      "Midwest specialty food wholesaler offering snacks, pantry staples, sauces, and beverage concentrates.",
  },
  {
    id: "evergreen-baby",
    name: "Evergreen Baby & Home",
    location: "Minneapolis, Minnesota",
    state: "Minnesota",
    businessType: "Brand Owner",
    yearFounded: 2016,
    yearsInBusiness: 10,
    categories: ["Home Goods", "Health & Wellness"],
    certifications: ["OEKO-TEX", "CPSIA Tested", "FSC"],
    exportCountries: ["South Korea", "Japan"],
    exportExperience:
      "Works with boutique importers on baby, family, and home products with safety documentation.",
    monthlyCapacity: "55,000 units",
    responseTime: "1 business day",
    paymentTerms: ["30% deposit / 70% before shipment", "Wire transfer"],
    incoterms: ["EXW", "FOB", "DDP"],
    documentsAvailable: [...commonDocuments, "Safety test reports", "Material declaration"],
    contactPerson: "Hannah Lee",
    contactEmail: "hello@evergreenbabyhome.example",
    website: "evergreenbabyhome.example",
    languages: ["English", "Korean"],
    rating: 4.6,
    reviewCount: 21,
    verified: true,
    description:
      "Family lifestyle brand offering soft goods, nursery organization, and home essentials for premium retail.",
  },
  {
    id: "nova-active",
    name: "Nova Active Supply",
    location: "Miami, Florida",
    state: "Florida",
    businessType: "Distributor",
    yearFounded: 2012,
    yearsInBusiness: 14,
    categories: ["Apparel", "Health & Wellness"],
    certifications: ["OEKO-TEX", "GRS"],
    exportCountries: ["South Korea", "Brazil", "Colombia"],
    exportExperience:
      "Exports activewear and wellness accessories with flexible assortment planning.",
    monthlyCapacity: "120,000 units",
    responseTime: "Under 10 hours",
    paymentTerms: ["Wire transfer", "Credit card for samples"],
    incoterms: ["EXW", "FOB", "CIF"],
    documentsAvailable: [...commonDocuments, "Fabric test reports"],
    contactPerson: "Isabella Cruz",
    contactEmail: "trade@novaactive.example",
    website: "novaactive.example",
    languages: ["English", "Spanish"],
    rating: 4.3,
    reviewCount: 19,
    verified: false,
    description:
      "Active lifestyle distributor for apparel, mats, bands, recovery tools, and wellness kits.",
  },
  {
    id: "golden-state-pantry",
    name: "Golden State Pantry",
    location: "Sacramento, California",
    state: "California",
    businessType: "Manufacturer",
    yearFounded: 2006,
    yearsInBusiness: 20,
    categories: ["Food & Beverage"],
    certifications: ["FDA Registered", "USDA Organic", "Kosher"],
    exportCountries: ["South Korea", "Japan", "Australia"],
    exportExperience:
      "Manufactures shelf-stable pantry products with strong documentation for grocery importers.",
    monthlyCapacity: "1.8 million units",
    responseTime: "Under 6 hours",
    paymentTerms: ["Wire transfer", "Letter of credit"],
    incoterms: ["FOB", "CIF", "DDP"],
    documentsAvailable: [...commonDocuments, "COA", "FDA registration", "Organic certificate"],
    contactPerson: "Ava Rodriguez",
    contactEmail: "global@goldenstatepantry.example",
    website: "goldenstatepantry.example",
    languages: ["English", "Spanish"],
    rating: 4.9,
    reviewCount: 82,
    verified: true,
    description:
      "California manufacturer of nut butters, granola, sauces, and better-for-you shelf-stable foods.",
  },
  {
    id: "cleanline-labs",
    name: "CleanLine Labs",
    location: "Boston, Massachusetts",
    state: "Massachusetts",
    businessType: "Manufacturer",
    yearFounded: 2010,
    yearsInBusiness: 16,
    categories: ["Beauty & Skincare", "Supplements"],
    certifications: ["GMP", "ISO 22716", "FDA Registered"],
    exportCountries: ["South Korea", "France", "Indonesia"],
    exportExperience:
      "Contract manufacturer for skincare, ingestible beauty, and private label beauty programs.",
    monthlyCapacity: "650,000 units",
    responseTime: "Under 8 hours",
    paymentTerms: ["50% deposit / 50% before shipment", "Wire transfer"],
    incoterms: ["EXW", "FOB", "CIF"],
    documentsAvailable: [...commonDocuments, "COA", "MSDS", "FDA registration"],
    contactPerson: "Liam Turner",
    contactEmail: "export@cleanlinelabs.example",
    website: "cleanlinelabs.example",
    languages: ["English"],
    rating: 4.7,
    reviewCount: 44,
    verified: true,
    description:
      "Lab-based manufacturer producing skincare, beauty supplements, and custom formulas for international buyers.",
  },
];

const koreanSellerProfiles: Array<Pick<
  Seller,
  | "id"
  | "name"
  | "location"
  | "state"
  | "contactPerson"
  | "contactEmail"
  | "website"
  | "languages"
  | "certifications"
  | "exportCountries"
  | "exportExperience"
  | "description"
>> = [
  {
    id: "pacific-naturals",
    name: "Seoul Glow Labs",
    location: "Seoul, South Korea",
    state: "Seoul",
    contactPerson: "Jiyeon Han",
    contactEmail: "exports@seoulglowlabs.example",
    website: "seoulglowlabs.example",
    languages: ["Korean", "English"],
    certifications: ["ISO 22716", "CGMP", "Vegan Certified"],
    exportCountries: ["United States", "Japan", "Singapore", "Canada"],
    exportExperience:
      "Exports K-beauty skincare and wellness products to U.S. retailers with English documentation and FDA-facing support.",
    description:
      "Korean clean beauty and wellness brand with private label capacity for U.S. retailers, importers, and specialty ecommerce channels.",
  },
  {
    id: "harbor-foods",
    name: "Busan Heritage Foods",
    location: "Busan, South Korea",
    state: "Busan",
    contactPerson: "Minjun Seo",
    contactEmail: "trade@busanheritagefoods.example",
    website: "busanheritagefoods.example",
    languages: ["Korean", "English"],
    certifications: ["HACCP", "FSSC 22000", "FDA Facility Registered"],
    exportCountries: ["United States", "Taiwan", "United Arab Emirates"],
    exportExperience:
      "Experienced with shelf-stable Korean food exports, FDA prior notice workflows, and U.S. importer documentation.",
    description:
      "Korean food exporter focused on premium snacks, beverages, sauces, pantry items, and retail-ready Korean flavors.",
  },
  {
    id: "atlas-apparel",
    name: "Daegu Textile Works",
    location: "Daegu, South Korea",
    state: "Daegu",
    contactPerson: "Sumin Kwon",
    contactEmail: "global@daegutextile.example",
    website: "daegutextile.example",
    languages: ["Korean", "English"],
    certifications: ["OEKO-TEX", "WRAP", "GRS"],
    exportCountries: ["United States", "Mexico", "Australia"],
    exportExperience:
      "Supports U.S. fashion buyers with private label apparel, size specs, hang tags, and carton labeling.",
    description:
      "Korean apparel manufacturer producing basics, athleisure, socks, and private label capsule programs for U.S. buyers.",
  },
  {
    id: "summit-nutrition",
    name: "Incheon Bio Nutrition",
    location: "Incheon, South Korea",
    state: "Incheon",
    contactPerson: "Hyun Park",
    contactEmail: "sales@incheonbionutrition.example",
    website: "incheonbionutrition.example",
    languages: ["Korean", "English"],
    certifications: ["GMP", "HACCP", "FDA Facility Registered"],
    exportCountries: ["United States", "Thailand", "Vietnam", "Germany"],
    exportExperience:
      "Exports supplements and functional foods with batch COA, ingredient disclosure, and U.S. label review support.",
    description:
      "Korean contract manufacturer and brand owner for gummies, powders, capsules, and functional wellness blends.",
  },
  {
    id: "hearth-home",
    name: "Gyeonggi Living Studio",
    location: "Seongnam, South Korea",
    state: "Gyeonggi-do",
    contactPerson: "Yerin Cho",
    contactEmail: "wholesale@gyeonggiliving.example",
    website: "gyeonggiliving.example",
    languages: ["Korean", "English"],
    certifications: ["KC", "FSC", "Prop 65 Tested"],
    exportCountries: ["United States", "Japan", "New Zealand"],
    exportExperience:
      "Ships Korean-designed home goods with retail packaging, carton specs, and U.S. compliance documentation.",
    description:
      "Korean home goods brand specializing in storage, kitchen, tabletop, and compact-living products for U.S. retail.",
  },
  {
    id: "bright-paws",
    name: "PawSeoul Collective",
    location: "Seoul, South Korea",
    state: "Seoul",
    contactPerson: "Doyun Lee",
    contactEmail: "export@pawseoul.example",
    website: "pawseoul.example",
    languages: ["Korean", "English"],
    certifications: ["HACCP", "AAFCO Label Review", "FDA Facility Registered"],
    exportCountries: ["United States", "Hong Kong", "Philippines"],
    exportExperience:
      "Exports pet treats, grooming, and accessories with ingredient statements and U.S. importer support.",
    description:
      "Premium Korean pet product supplier with clean packaging formats and export-ready pet care assortments.",
  },
  {
    id: "blue-ridge-wellness",
    name: "Jeju Wellness House",
    location: "Jeju, South Korea",
    state: "Jeju",
    contactPerson: "Haein Kim",
    contactEmail: "partners@jejuwellnesshouse.example",
    website: "jejuwellnesshouse.example",
    languages: ["Korean", "English"],
    certifications: ["ISO 22716", "Vegan Certified", "USDA Organic Ingredients"],
    exportCountries: ["United States", "United Kingdom", "Singapore"],
    exportExperience:
      "Supports U.S. wellness buyers with natural personal care, aromatherapy, and export documentation.",
    description:
      "Jeju-based wellness company offering aromatherapy, personal care, and herbal products for premium U.S. retail.",
  },
  {
    id: "frontier-gourmet",
    name: "K-Food Frontier",
    location: "Daejeon, South Korea",
    state: "Daejeon",
    contactPerson: "Taeyang Yoo",
    contactEmail: "exports@kfoodfrontier.example",
    website: "kfoodfrontier.example",
    languages: ["Korean", "English"],
    certifications: ["HACCP", "FSSC 22000", "FDA Facility Registered"],
    exportCountries: ["United States", "Malaysia", "Chile"],
    exportExperience:
      "Multi-brand Korean food exporter with consolidated pallet programs for U.S. importers.",
    description:
      "Korean specialty food wholesaler offering snacks, pantry staples, sauces, and beverage concentrates for U.S. buyers.",
  },
  {
    id: "evergreen-baby",
    name: "Evergreen Seoul Baby & Home",
    location: "Suwon, South Korea",
    state: "Gyeonggi-do",
    contactPerson: "Nari Jung",
    contactEmail: "hello@evergreenseoul.example",
    website: "evergreenseoul.example",
    languages: ["Korean", "English"],
    certifications: ["OEKO-TEX", "KC", "CPSIA Tested"],
    exportCountries: ["United States", "Japan"],
    exportExperience:
      "Works with boutique U.S. importers on baby, family, and home products with safety documentation.",
    description:
      "Korean family lifestyle brand offering soft goods, nursery organization, and home essentials for premium U.S. retail.",
  },
  {
    id: "nova-active",
    name: "Seoul Active Supply",
    location: "Seoul, South Korea",
    state: "Seoul",
    contactPerson: "Ara Shin",
    contactEmail: "trade@seoulactive.example",
    website: "seoulactive.example",
    languages: ["Korean", "English"],
    certifications: ["OEKO-TEX", "GRS"],
    exportCountries: ["United States", "Brazil", "Colombia"],
    exportExperience:
      "Exports Korean activewear and wellness accessories with flexible U.S. assortment planning.",
    description:
      "Korean active lifestyle distributor for apparel, mats, bands, recovery tools, and wellness kits.",
  },
  {
    id: "golden-state-pantry",
    name: "Han River Pantry",
    location: "Gwangju, South Korea",
    state: "Gwangju",
    contactPerson: "Jina Baek",
    contactEmail: "global@hanriverpantry.example",
    website: "hanriverpantry.example",
    languages: ["Korean", "English"],
    certifications: ["HACCP", "FDA Facility Registered", "Kosher"],
    exportCountries: ["United States", "Japan", "Australia"],
    exportExperience:
      "Manufactures shelf-stable Korean pantry products with documentation for U.S. grocery importers.",
    description:
      "Korean manufacturer of sauces, granola, snacks, and better-for-you shelf-stable foods for U.S. channels.",
  },
  {
    id: "cleanline-labs",
    name: "CleanLine Seoul Labs",
    location: "Seoul, South Korea",
    state: "Seoul",
    contactPerson: "Junho Chae",
    contactEmail: "export@cleanlineseoul.example",
    website: "cleanlineseoul.example",
    languages: ["Korean", "English"],
    certifications: ["CGMP", "ISO 22716", "FDA Facility Registered"],
    exportCountries: ["United States", "France", "Indonesia"],
    exportExperience:
      "Contract manufacturer for K-beauty skincare, ingestible beauty, and private label programs for U.S. buyers.",
    description:
      "Korean lab-based manufacturer producing skincare, beauty supplements, and custom formulas for international buyers.",
  },
];

export const sellers: Seller[] = baseSellers.map((seller) => ({
  ...seller,
  ...koreanSellerProfiles.find((profile) => profile.id === seller.id),
  useDefaultLogo: true,
  verificationStatus: "verified",
}));

const imageByCategory: Record<ProductCategory, string> = {
  "Beauty & Skincare":
    "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=900&q=80",
  "Food & Beverage":
    "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=900&q=80",
  Apparel:
    "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=900&q=80",
  Supplements:
    "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=900&q=80",
  "Home Goods":
    "https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?auto=format&fit=crop&w=900&q=80",
  "Pet Products":
    "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=900&q=80",
  "Health & Wellness":
    "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=900&q=80",
};

const riskNotes = [
  "Buyer should verify import requirements before purchase.",
  "Regulatory requirements vary by category.",
];

const baseProducts: Product[] = [
  {
    id: "blueberry-collagen-gummies",
    name: "Blueberry Collagen Gummies",
    category: "Supplements",
    sellerId: "summit-nutrition",
    sellerName: "Summit Nutrition Labs",
    sellerLocation: "Salt Lake City, Utah",
    shortDescription: "Low-sugar beauty gummies with collagen peptides and vitamin C.",
    longDescription:
      "A shelf-stable gummy supplement designed for beauty-from-within retail programs. Available in branded or private label formats with batch-level documentation.",
    wholesalePrice: "$4.85 / bottle",
    wholesalePriceValue: 4.85,
    moq: "1,200 bottles",
    moqUnits: 1200,
    leadTime: "21-28 days",
    monthlyCapacity: "240,000 bottles",
    sampleAvailable: true,
    privateLabelAvailable: true,
    countryOfOrigin: "United States",
    shippingOrigin: "Salt Lake City, UT",
    incoterms: ["EXW", "FOB", "CIF"],
    hsCode: "2106.90",
    certifications: ["GMP", "NSF", "FDA Registered"],
    documentsAvailable: [...commonDocuments, "COA", "FDA registration"],
    shelfLife: "24 months",
    packageSize: "90 gummies / 180 g bottle",
    unitsPerCarton: "24 bottles",
    cartonWeight: "7.8 kg",
    koreanMarketFit:
      "Beauty supplements perform strongly across Korean online channels when positioned around convenience, flavor, and ingredient transparency.",
    suggestedSalesChannels: ["Coupang", "Naver Smart Store", "Olive Young"],
    riskNotes,
    imagePlaceholder: imageByCategory["Supplements"],
  },
  {
    id: "ceramide-barrier-cream",
    name: "Ceramide Barrier Cream",
    category: "Beauty & Skincare",
    sellerId: "pacific-naturals",
    sellerName: "Pacific Naturals Co.",
    sellerLocation: "Los Angeles, California",
    shortDescription: "Fragrance-free daily moisturizer for dry and sensitive skin.",
    longDescription:
      "A dermatologist-tested facial cream with ceramides, oat extract, and squalane. Built for pharmacy, clean beauty, and cross-border ecommerce assortments.",
    wholesalePrice: "$3.90 / tube",
    wholesalePriceValue: 3.9,
    moq: "2,000 tubes",
    moqUnits: 2000,
    leadTime: "30 days",
    monthlyCapacity: "180,000 tubes",
    sampleAvailable: true,
    privateLabelAvailable: true,
    countryOfOrigin: "United States",
    shippingOrigin: "Los Angeles, CA",
    incoterms: ["EXW", "FOB", "CIF", "DDP"],
    hsCode: "3304.99",
    certifications: ["GMP", "Leaping Bunny"],
    documentsAvailable: [...commonDocuments, "COA", "MSDS"],
    shelfLife: "30 months",
    packageSize: "75 ml tube",
    unitsPerCarton: "96 tubes",
    cartonWeight: "10.4 kg",
    koreanMarketFit:
      "Barrier repair and sensitive-skin positioning fit Korean skincare demand for gentle daily products.",
    suggestedSalesChannels: ["Olive Young", "Naver Smart Store", "Specialty retail stores"],
    riskNotes,
    imagePlaceholder: imageByCategory["Beauty & Skincare"],
  },
  {
    id: "organic-almond-butter-cups",
    name: "Organic Almond Butter Cups",
    category: "Food & Beverage",
    sellerId: "golden-state-pantry",
    sellerName: "Golden State Pantry",
    sellerLocation: "Sacramento, California",
    shortDescription: "Organic chocolate cups filled with roasted almond butter.",
    longDescription:
      "Premium shelf-stable confectionery packed for convenience stores, online snack boxes, and specialty grocery programs.",
    wholesalePrice: "$1.28 / pack",
    wholesalePriceValue: 1.28,
    moq: "10,000 packs",
    moqUnits: 10000,
    leadTime: "18-24 days",
    monthlyCapacity: "900,000 packs",
    sampleAvailable: true,
    privateLabelAvailable: false,
    countryOfOrigin: "United States",
    shippingOrigin: "Oakland, CA",
    incoterms: ["FOB", "CIF", "DDP"],
    hsCode: "1806.90",
    certifications: ["FDA Registered", "USDA Organic", "Kosher"],
    documentsAvailable: [...commonDocuments, "COA", "FDA registration", "Organic certificate"],
    shelfLife: "12 months",
    packageSize: "42 g twin pack",
    unitsPerCarton: "144 packs",
    cartonWeight: "8.5 kg",
    koreanMarketFit:
      "Better-for-you chocolate snacks align with premium snack gifting and convenience retail demand.",
    suggestedSalesChannels: ["Convenience stores", "Coupang", "Department stores"],
    riskNotes,
    imagePlaceholder: imageByCategory["Food & Beverage"],
  },
  {
    id: "recycled-cotton-crewneck",
    name: "Recycled Cotton Crewneck",
    category: "Apparel",
    sellerId: "atlas-apparel",
    sellerName: "Atlas Apparel Supply",
    sellerLocation: "Portland, Oregon",
    shortDescription: "Midweight unisex sweatshirt made with recycled cotton blend fleece.",
    longDescription:
      "A premium blank or private label crewneck with export carton labels, color cards, and size-grade documentation.",
    wholesalePrice: "$12.40 / unit",
    wholesalePriceValue: 12.4,
    moq: "600 units",
    moqUnits: 600,
    leadTime: "35-45 days",
    monthlyCapacity: "35,000 units",
    sampleAvailable: true,
    privateLabelAvailable: true,
    countryOfOrigin: "United States",
    shippingOrigin: "Portland, OR",
    incoterms: ["EXW", "FOB"],
    hsCode: "6110.20",
    certifications: ["OEKO-TEX", "WRAP"],
    documentsAvailable: [...commonDocuments, "Fabric composition sheet", "Test reports"],
    packageSize: "S-XL assorted, polybag optional",
    unitsPerCarton: "24 units",
    cartonWeight: "12.1 kg",
    koreanMarketFit:
      "Minimal, sustainable basics are a strong fit for Korean lifestyle boutiques and online fashion sellers.",
    suggestedSalesChannels: ["Naver Smart Store", "Specialty retail stores", "Offline wholesale"],
    riskNotes,
    imagePlaceholder: imageByCategory["Apparel"],
  },
  {
    id: "modular-bamboo-drawer-box",
    name: "Modular Bamboo Drawer Box",
    category: "Home Goods",
    sellerId: "hearth-home",
    sellerName: "Hearth & Home Goods",
    sellerLocation: "Austin, Texas",
    shortDescription: "Stackable bamboo organizer for kitchen, vanity, and desk drawers.",
    longDescription:
      "Retail-ready organizer system with minimalist packaging and FSC documentation for premium home channels.",
    wholesalePrice: "$6.75 / unit",
    wholesalePriceValue: 6.75,
    moq: "800 units",
    moqUnits: 800,
    leadTime: "25-35 days",
    monthlyCapacity: "40,000 units",
    sampleAvailable: true,
    privateLabelAvailable: true,
    countryOfOrigin: "United States",
    shippingOrigin: "Houston, TX",
    incoterms: ["EXW", "FOB", "DDP"],
    hsCode: "4419.90",
    certifications: ["FSC", "Prop 65 Tested"],
    documentsAvailable: [...commonDocuments, "Material safety sheet", "Test reports"],
    packageSize: "30 x 15 x 7 cm retail box",
    unitsPerCarton: "18 units",
    cartonWeight: "11.6 kg",
    koreanMarketFit:
      "Small-space organization and natural materials work well for Korean apartment living and lifestyle retail.",
    suggestedSalesChannels: ["Department stores", "Naver Smart Store", "Specialty retail stores"],
    riskNotes,
    imagePlaceholder: imageByCategory["Home Goods"],
  },
  {
    id: "freeze-dried-salmon-treats",
    name: "Freeze-Dried Salmon Treats",
    category: "Pet Products",
    sellerId: "bright-paws",
    sellerName: "Bright Paws Collective",
    sellerLocation: "Denver, Colorado",
    shortDescription: "Single-ingredient salmon treats for dogs and cats.",
    longDescription:
      "Premium high-protein pet treats with clean labeling and export-ready ingredient documentation.",
    wholesalePrice: "$2.95 / pouch",
    wholesalePriceValue: 2.95,
    moq: "3,000 pouches",
    moqUnits: 3000,
    leadTime: "20-30 days",
    monthlyCapacity: "220,000 pouches",
    sampleAvailable: true,
    privateLabelAvailable: true,
    countryOfOrigin: "United States",
    shippingOrigin: "Denver, CO",
    incoterms: ["FOB", "CIF", "DDP"],
    hsCode: "2309.10",
    certifications: ["FDA Registered", "AAFCO Compliant"],
    documentsAvailable: [...commonDocuments, "COA", "Health certificate", "Ingredient statement"],
    shelfLife: "18 months",
    packageSize: "60 g resealable pouch",
    unitsPerCarton: "80 pouches",
    cartonWeight: "6.3 kg",
    koreanMarketFit:
      "Premium pet treats with simple ingredients match Korea's fast-growing pet family segment.",
    suggestedSalesChannels: ["Coupang", "Pet specialty retail", "Naver Smart Store"],
    riskNotes,
    imagePlaceholder: imageByCategory["Pet Products"],
  },
  {
    id: "magnesium-sleep-powder",
    name: "Magnesium Sleep Powder",
    category: "Health & Wellness",
    sellerId: "blue-ridge-wellness",
    sellerName: "Blue Ridge Wellness",
    sellerLocation: "Asheville, North Carolina",
    shortDescription: "Caffeine-free berry powder with magnesium glycinate and L-theanine.",
    longDescription:
      "Functional evening wellness powder for sachet or jar programs, designed around calm and recovery positioning.",
    wholesalePrice: "$5.60 / jar",
    wholesalePriceValue: 5.6,
    moq: "1,500 jars",
    moqUnits: 1500,
    leadTime: "28 days",
    monthlyCapacity: "115,000 jars",
    sampleAvailable: true,
    privateLabelAvailable: true,
    countryOfOrigin: "United States",
    shippingOrigin: "Charlotte, NC",
    incoterms: ["EXW", "FOB"],
    hsCode: "2106.90",
    certifications: ["USDA Organic", "GMP"],
    documentsAvailable: [...commonDocuments, "COA", "Organic certificate"],
    shelfLife: "24 months",
    packageSize: "180 g jar",
    unitsPerCarton: "24 jars",
    cartonWeight: "8.9 kg",
    koreanMarketFit:
      "Sleep and stress support products are increasingly visible in Korean wellness and direct-to-consumer channels.",
    suggestedSalesChannels: ["Naver Smart Store", "Coupang", "Specialty retail stores"],
    riskNotes,
    imagePlaceholder: imageByCategory["Health & Wellness"],
  },
  {
    id: "sparkling-maple-tonic",
    name: "Sparkling Maple Tonic",
    category: "Food & Beverage",
    sellerId: "harbor-foods",
    sellerName: "Harbor Foods Export",
    sellerLocation: "Seattle, Washington",
    shortDescription: "Lightly sweet sparkling beverage made with real maple water.",
    longDescription:
      "Shelf-stable premium beverage for cafes, grocers, and online gifting assortments.",
    wholesalePrice: "$0.92 / can",
    wholesalePriceValue: 0.92,
    moq: "24,000 cans",
    moqUnits: 24000,
    leadTime: "16-22 days",
    monthlyCapacity: "1.2 million cans",
    sampleAvailable: true,
    privateLabelAvailable: false,
    countryOfOrigin: "United States",
    shippingOrigin: "Seattle, WA",
    incoterms: ["FOB", "CIF", "DDP"],
    hsCode: "2202.10",
    certifications: ["FDA Registered", "SQF", "Kosher"],
    documentsAvailable: [...commonDocuments, "FDA registration", "COA"],
    shelfLife: "15 months",
    packageSize: "355 ml can",
    unitsPerCarton: "24 cans",
    cartonWeight: "9.4 kg",
    koreanMarketFit:
      "Low-sugar premium sparkling drinks fit cafe, convenience, and online discovery channels.",
    suggestedSalesChannels: ["Convenience stores", "Department stores", "Coupang"],
    riskNotes,
    imagePlaceholder: imageByCategory["Food & Beverage"],
  },
  {
    id: "azelaic-acid-serum",
    name: "Azelaic Acid Clarifying Serum",
    category: "Beauty & Skincare",
    sellerId: "cleanline-labs",
    sellerName: "CleanLine Labs",
    sellerLocation: "Boston, Massachusetts",
    shortDescription: "Lightweight serum for visible redness and uneven tone.",
    longDescription:
      "Lab-formulated facial serum with clean clinical positioning and documentation for ingredient review.",
    wholesalePrice: "$4.35 / bottle",
    wholesalePriceValue: 4.35,
    moq: "2,500 bottles",
    moqUnits: 2500,
    leadTime: "32-40 days",
    monthlyCapacity: "250,000 bottles",
    sampleAvailable: true,
    privateLabelAvailable: true,
    countryOfOrigin: "United States",
    shippingOrigin: "Boston, MA",
    incoterms: ["EXW", "FOB", "CIF"],
    hsCode: "3304.99",
    certifications: ["GMP", "ISO 22716"],
    documentsAvailable: [...commonDocuments, "COA", "MSDS"],
    shelfLife: "30 months",
    packageSize: "30 ml glass dropper",
    unitsPerCarton: "120 bottles",
    cartonWeight: "14.2 kg",
    koreanMarketFit:
      "Tone and redness care are familiar skincare concerns for Korean beauty consumers.",
    suggestedSalesChannels: ["Olive Young", "Naver Smart Store", "Specialty retail stores"],
    riskNotes,
    imagePlaceholder: imageByCategory["Beauty & Skincare"],
  },
  {
    id: "plant-protein-crunch-bars",
    name: "Plant Protein Crunch Bars",
    category: "Food & Beverage",
    sellerId: "frontier-gourmet",
    sellerName: "Frontier Gourmet Group",
    sellerLocation: "Chicago, Illinois",
    shortDescription: "Vegan protein snack bars with pea protein crisps.",
    longDescription:
      "Shelf-stable nutrition bar with clean packaging, suitable for gyms, convenience, and online snack bundles.",
    wholesalePrice: "$1.05 / bar",
    wholesalePriceValue: 1.05,
    moq: "15,000 bars",
    moqUnits: 15000,
    leadTime: "20 days",
    monthlyCapacity: "1 million bars",
    sampleAvailable: true,
    privateLabelAvailable: true,
    countryOfOrigin: "United States",
    shippingOrigin: "Chicago, IL",
    incoterms: ["FOB", "CIF"],
    hsCode: "1905.90",
    certifications: ["FDA Registered", "SQF", "Non-GMO Project"],
    documentsAvailable: [...commonDocuments, "COA", "FDA registration"],
    shelfLife: "12 months",
    packageSize: "55 g bar",
    unitsPerCarton: "144 bars",
    cartonWeight: "9.1 kg",
    koreanMarketFit:
      "Protein snacking is growing across Korean fitness and convenience channels.",
    suggestedSalesChannels: ["Coupang", "Convenience stores", "Gyms"],
    riskNotes,
    imagePlaceholder: imageByCategory["Food & Beverage"],
  },
  {
    id: "pima-cotton-tee-pack",
    name: "Pima Cotton Tee Pack",
    category: "Apparel",
    sellerId: "atlas-apparel",
    sellerName: "Atlas Apparel Supply",
    sellerLocation: "Portland, Oregon",
    shortDescription: "Premium blank tee three-pack with soft-hand Pima cotton.",
    longDescription:
      "Retail-ready essentials pack with minimalist branding options and strong margin profile for online fashion sellers.",
    wholesalePrice: "$8.80 / pack",
    wholesalePriceValue: 8.8,
    moq: "900 packs",
    moqUnits: 900,
    leadTime: "30-40 days",
    monthlyCapacity: "40,000 packs",
    sampleAvailable: true,
    privateLabelAvailable: true,
    countryOfOrigin: "United States",
    shippingOrigin: "Portland, OR",
    incoterms: ["EXW", "FOB"],
    hsCode: "6109.10",
    certifications: ["OEKO-TEX", "WRAP"],
    documentsAvailable: [...commonDocuments, "Fabric composition sheet"],
    packageSize: "Three shirts per paper sleeve",
    unitsPerCarton: "30 packs",
    cartonWeight: "13.5 kg",
    koreanMarketFit:
      "Premium basics with clean packaging work across lifestyle boutiques and online brand shops.",
    suggestedSalesChannels: ["Naver Smart Store", "Specialty retail stores"],
    riskNotes,
    imagePlaceholder: imageByCategory["Apparel"],
  },
  {
    id: "silicone-free-hair-oil",
    name: "Silicone-Free Hair Oil",
    category: "Beauty & Skincare",
    sellerId: "pacific-naturals",
    sellerName: "Pacific Naturals Co.",
    sellerLocation: "Los Angeles, California",
    shortDescription: "Lightweight hair oil with argan, jojoba, and meadowfoam seed oil.",
    longDescription:
      "Clean hair treatment oil with premium glass packaging and export documentation for cosmetic importers.",
    wholesalePrice: "$3.25 / bottle",
    wholesalePriceValue: 3.25,
    moq: "2,400 bottles",
    moqUnits: 2400,
    leadTime: "24-30 days",
    monthlyCapacity: "160,000 bottles",
    sampleAvailable: true,
    privateLabelAvailable: true,
    countryOfOrigin: "United States",
    shippingOrigin: "Los Angeles, CA",
    incoterms: ["EXW", "FOB", "CIF", "DDP"],
    hsCode: "3305.90",
    certifications: ["GMP", "Leaping Bunny"],
    documentsAvailable: [...commonDocuments, "COA", "MSDS"],
    shelfLife: "30 months",
    packageSize: "50 ml glass pump",
    unitsPerCarton: "96 bottles",
    cartonWeight: "12.7 kg",
    koreanMarketFit:
      "Hair repair and clean beauty positioning are strong fits for premium Korean beauty retail.",
    suggestedSalesChannels: ["Olive Young", "Naver Smart Store", "Specialty retail stores"],
    riskNotes,
    imagePlaceholder: imageByCategory["Beauty & Skincare"],
  },
  {
    id: "ceramic-meal-prep-bowls",
    name: "Ceramic Meal Prep Bowls",
    category: "Home Goods",
    sellerId: "hearth-home",
    sellerName: "Hearth & Home Goods",
    sellerLocation: "Austin, Texas",
    shortDescription: "Stackable ceramic bowls with vented silicone lids.",
    longDescription:
      "Premium kitchen storage set for home organization, lunch prep, and department store lifestyle assortments.",
    wholesalePrice: "$9.60 / set",
    wholesalePriceValue: 9.6,
    moq: "600 sets",
    moqUnits: 600,
    leadTime: "35 days",
    monthlyCapacity: "24,000 sets",
    sampleAvailable: true,
    privateLabelAvailable: true,
    countryOfOrigin: "United States",
    shippingOrigin: "Houston, TX",
    incoterms: ["EXW", "FOB", "DDP"],
    hsCode: "6912.00",
    certifications: ["Prop 65 Tested"],
    documentsAvailable: [...commonDocuments, "Material safety sheet", "Drop test report"],
    packageSize: "Set of 3 bowls in retail box",
    unitsPerCarton: "8 sets",
    cartonWeight: "16.2 kg",
    koreanMarketFit:
      "Meal prep and tidy kitchen storage products appeal to apartment households and premium home channels.",
    suggestedSalesChannels: ["Department stores", "Naver Smart Store", "Specialty retail stores"],
    riskNotes,
    imagePlaceholder: imageByCategory["Home Goods"],
  },
  {
    id: "calming-pet-shampoo",
    name: "Calming Oat Pet Shampoo",
    category: "Pet Products",
    sellerId: "bright-paws",
    sellerName: "Bright Paws Collective",
    sellerLocation: "Denver, Colorado",
    shortDescription: "Gentle oatmeal shampoo for dogs with sensitive skin.",
    longDescription:
      "Clean pet grooming product with mild scent, retail-ready packaging, and private label options.",
    wholesalePrice: "$2.40 / bottle",
    wholesalePriceValue: 2.4,
    moq: "3,600 bottles",
    moqUnits: 3600,
    leadTime: "26-34 days",
    monthlyCapacity: "180,000 bottles",
    sampleAvailable: true,
    privateLabelAvailable: true,
    countryOfOrigin: "United States",
    shippingOrigin: "Denver, CO",
    incoterms: ["FOB", "CIF", "DDP"],
    hsCode: "3307.90",
    certifications: ["FDA Registered", "Cruelty Free"],
    documentsAvailable: [...commonDocuments, "COA", "MSDS"],
    shelfLife: "30 months",
    packageSize: "355 ml bottle",
    unitsPerCarton: "48 bottles",
    cartonWeight: "19.8 kg",
    koreanMarketFit:
      "Gentle grooming is a strong fit for Korea's premium pet care and grooming shop channels.",
    suggestedSalesChannels: ["Pet specialty retail", "Coupang", "Naver Smart Store"],
    riskNotes,
    imagePlaceholder: imageByCategory["Pet Products"],
  },
  {
    id: "electrolyte-stick-packs",
    name: "Electrolyte Stick Packs",
    category: "Health & Wellness",
    sellerId: "summit-nutrition",
    sellerName: "Summit Nutrition Labs",
    sellerLocation: "Salt Lake City, Utah",
    shortDescription: "Sugar-free hydration powder in citrus and peach flavors.",
    longDescription:
      "Portable hydration sticks for sports, office, and travel merchandising with carton-ready display options.",
    wholesalePrice: "$0.36 / stick",
    wholesalePriceValue: 0.36,
    moq: "60,000 sticks",
    moqUnits: 60000,
    leadTime: "25-32 days",
    monthlyCapacity: "3 million sticks",
    sampleAvailable: true,
    privateLabelAvailable: true,
    countryOfOrigin: "United States",
    shippingOrigin: "Salt Lake City, UT",
    incoterms: ["EXW", "FOB", "CIF"],
    hsCode: "2106.90",
    certifications: ["GMP", "NSF", "FDA Registered"],
    documentsAvailable: [...commonDocuments, "COA", "FDA registration"],
    shelfLife: "24 months",
    packageSize: "5 g stick",
    unitsPerCarton: "1,000 sticks",
    cartonWeight: "7.1 kg",
    koreanMarketFit:
      "Portable functional hydration fits offices, fitness studios, golf, and online wellness bundles.",
    suggestedSalesChannels: ["Coupang", "Gyms", "Naver Smart Store"],
    riskNotes,
    imagePlaceholder: imageByCategory["Health & Wellness"],
  },
  {
    id: "cold-brew-oat-latte",
    name: "Cold Brew Oat Latte",
    category: "Food & Beverage",
    sellerId: "harbor-foods",
    sellerName: "Harbor Foods Export",
    sellerLocation: "Seattle, Washington",
    shortDescription: "Ready-to-drink oat milk cold brew in slim cans.",
    longDescription:
      "Shelf-stable coffee beverage with cafe-quality flavor and clean ingredient positioning.",
    wholesalePrice: "$1.12 / can",
    wholesalePriceValue: 1.12,
    moq: "24,000 cans",
    moqUnits: 24000,
    leadTime: "18-24 days",
    monthlyCapacity: "900,000 cans",
    sampleAvailable: true,
    privateLabelAvailable: false,
    countryOfOrigin: "United States",
    shippingOrigin: "Seattle, WA",
    incoterms: ["FOB", "CIF", "DDP"],
    hsCode: "2202.99",
    certifications: ["FDA Registered", "SQF"],
    documentsAvailable: [...commonDocuments, "FDA registration", "COA"],
    shelfLife: "12 months",
    packageSize: "250 ml can",
    unitsPerCarton: "24 cans",
    cartonWeight: "7.2 kg",
    koreanMarketFit:
      "RTD coffee is a familiar category in Korea, while oat milk gives it a premium imported angle.",
    suggestedSalesChannels: ["Convenience stores", "Cafes", "Coupang"],
    riskNotes,
    imagePlaceholder: imageByCategory["Food & Beverage"],
  },
  {
    id: "bamboo-baby-washcloths",
    name: "Bamboo Baby Washcloths",
    category: "Home Goods",
    sellerId: "evergreen-baby",
    sellerName: "Evergreen Baby & Home",
    sellerLocation: "Minneapolis, Minnesota",
    shortDescription: "Ultra-soft bamboo blend washcloth set for babies and family care.",
    longDescription:
      "Giftable soft goods set with safety documentation and clean retail packaging for premium baby channels.",
    wholesalePrice: "$3.80 / set",
    wholesalePriceValue: 3.8,
    moq: "1,200 sets",
    moqUnits: 1200,
    leadTime: "28-36 days",
    monthlyCapacity: "45,000 sets",
    sampleAvailable: true,
    privateLabelAvailable: true,
    countryOfOrigin: "United States",
    shippingOrigin: "Minneapolis, MN",
    incoterms: ["EXW", "FOB", "DDP"],
    hsCode: "6302.60",
    certifications: ["OEKO-TEX", "CPSIA Tested"],
    documentsAvailable: [...commonDocuments, "Safety test reports", "Material declaration"],
    packageSize: "Six cloths per paper box",
    unitsPerCarton: "48 sets",
    cartonWeight: "8.6 kg",
    koreanMarketFit:
      "Premium baby basics and gift sets fit department stores and curated online baby shops.",
    suggestedSalesChannels: ["Department stores", "Naver Smart Store", "Specialty retail stores"],
    riskNotes,
    imagePlaceholder: imageByCategory["Home Goods"],
  },
  {
    id: "seamless-yoga-set",
    name: "Seamless Yoga Set",
    category: "Apparel",
    sellerId: "nova-active",
    sellerName: "Nova Active Supply",
    sellerLocation: "Miami, Florida",
    shortDescription: "Two-piece ribbed yoga set with recycled nylon blend.",
    longDescription:
      "Retail-ready activewear set with seasonal colors, size curves, and flexible assortment support.",
    wholesalePrice: "$15.50 / set",
    wholesalePriceValue: 15.5,
    moq: "500 sets",
    moqUnits: 500,
    leadTime: "32-45 days",
    monthlyCapacity: "38,000 sets",
    sampleAvailable: true,
    privateLabelAvailable: true,
    countryOfOrigin: "United States",
    shippingOrigin: "Miami, FL",
    incoterms: ["EXW", "FOB", "CIF"],
    hsCode: "6211.43",
    certifications: ["OEKO-TEX", "GRS"],
    documentsAvailable: [...commonDocuments, "Fabric test reports"],
    packageSize: "Top and legging per polybag",
    unitsPerCarton: "24 sets",
    cartonWeight: "13.8 kg",
    koreanMarketFit:
      "Activewear with premium color stories performs well through fitness influencers and online fashion shops.",
    suggestedSalesChannels: ["Naver Smart Store", "Specialty retail stores", "Gyms"],
    riskNotes,
    imagePlaceholder: imageByCategory["Apparel"],
  },
  {
    id: "vegan-retinol-night-oil",
    name: "Vegan Retinol Night Oil",
    category: "Beauty & Skincare",
    sellerId: "blue-ridge-wellness",
    sellerName: "Blue Ridge Wellness",
    sellerLocation: "Asheville, North Carolina",
    shortDescription: "Bakuchiol-based night oil for a gentle retinol alternative.",
    longDescription:
      "Natural facial oil positioned for sensitive skin consumers seeking glow and texture care without harsh actives.",
    wholesalePrice: "$4.10 / bottle",
    wholesalePriceValue: 4.1,
    moq: "1,800 bottles",
    moqUnits: 1800,
    leadTime: "25-32 days",
    monthlyCapacity: "120,000 bottles",
    sampleAvailable: true,
    privateLabelAvailable: true,
    countryOfOrigin: "United States",
    shippingOrigin: "Charlotte, NC",
    incoterms: ["EXW", "FOB"],
    hsCode: "3304.99",
    certifications: ["USDA Organic", "Cruelty Free"],
    documentsAvailable: [...commonDocuments, "COA", "Organic certificate", "MSDS"],
    shelfLife: "24 months",
    packageSize: "30 ml glass dropper",
    unitsPerCarton: "120 bottles",
    cartonWeight: "14 kg",
    koreanMarketFit:
      "Gentle active alternatives and glow care fit Korea's ingredient-aware beauty audience.",
    suggestedSalesChannels: ["Olive Young", "Naver Smart Store"],
    riskNotes,
    imagePlaceholder: imageByCategory["Beauty & Skincare"],
  },
  {
    id: "pumpkin-spice-granola",
    name: "Pumpkin Spice Granola",
    category: "Food & Beverage",
    sellerId: "golden-state-pantry",
    sellerName: "Golden State Pantry",
    sellerLocation: "Sacramento, California",
    shortDescription: "Seasonal oat granola with pumpkin seeds, cinnamon, and maple.",
    longDescription:
      "Shelf-stable premium granola designed for grocery, cafe, and imported seasonal food assortments.",
    wholesalePrice: "$2.35 / pouch",
    wholesalePriceValue: 2.35,
    moq: "5,000 pouches",
    moqUnits: 5000,
    leadTime: "18-24 days",
    monthlyCapacity: "420,000 pouches",
    sampleAvailable: true,
    privateLabelAvailable: true,
    countryOfOrigin: "United States",
    shippingOrigin: "Oakland, CA",
    incoterms: ["FOB", "CIF", "DDP"],
    hsCode: "1904.20",
    certifications: ["FDA Registered", "USDA Organic", "Kosher"],
    documentsAvailable: [...commonDocuments, "COA", "FDA registration", "Organic certificate"],
    shelfLife: "10 months",
    packageSize: "340 g resealable pouch",
    unitsPerCarton: "24 pouches",
    cartonWeight: "10.6 kg",
    koreanMarketFit:
      "Imported seasonal flavors are useful for gift, cafe, and premium grocery merchandising.",
    suggestedSalesChannels: ["Department stores", "Cafes", "Coupang"],
    riskNotes,
    imagePlaceholder: imageByCategory["Food & Beverage"],
  },
  {
    id: "probiotic-dog-chews",
    name: "Probiotic Dog Chews",
    category: "Pet Products",
    sellerId: "bright-paws",
    sellerName: "Bright Paws Collective",
    sellerLocation: "Denver, Colorado",
    shortDescription: "Soft chews with probiotics and pumpkin for digestive support.",
    longDescription:
      "Functional pet supplement chews with clean ingredient documentation and retail display cartons.",
    wholesalePrice: "$3.70 / jar",
    wholesalePriceValue: 3.7,
    moq: "2,400 jars",
    moqUnits: 2400,
    leadTime: "28-35 days",
    monthlyCapacity: "150,000 jars",
    sampleAvailable: true,
    privateLabelAvailable: true,
    countryOfOrigin: "United States",
    shippingOrigin: "Denver, CO",
    incoterms: ["FOB", "CIF", "DDP"],
    hsCode: "2309.10",
    certifications: ["FDA Registered", "AAFCO Compliant"],
    documentsAvailable: [...commonDocuments, "COA", "Ingredient statement"],
    shelfLife: "18 months",
    packageSize: "90-count jar",
    unitsPerCarton: "24 jars",
    cartonWeight: "10.2 kg",
    koreanMarketFit:
      "Pet wellness formats are gaining visibility as Korean consumers spend more on functional pet care.",
    suggestedSalesChannels: ["Pet specialty retail", "Coupang", "Naver Smart Store"],
    riskNotes,
    imagePlaceholder: imageByCategory["Pet Products"],
  },
  {
    id: "collapsible-fabric-bins",
    name: "Collapsible Fabric Storage Bins",
    category: "Home Goods",
    sellerId: "evergreen-baby",
    sellerName: "Evergreen Baby & Home",
    sellerLocation: "Minneapolis, Minnesota",
    shortDescription: "Soft storage bins for nursery, closet, and apartment organization.",
    longDescription:
      "Fold-flat home organization product with neutral colors, safety reports, and private label options.",
    wholesalePrice: "$4.65 / unit",
    wholesalePriceValue: 4.65,
    moq: "1,000 units",
    moqUnits: 1000,
    leadTime: "30-40 days",
    monthlyCapacity: "50,000 units",
    sampleAvailable: true,
    privateLabelAvailable: true,
    countryOfOrigin: "United States",
    shippingOrigin: "Minneapolis, MN",
    incoterms: ["EXW", "FOB", "DDP"],
    hsCode: "6307.90",
    certifications: ["OEKO-TEX"],
    documentsAvailable: [...commonDocuments, "Material declaration", "Safety test reports"],
    packageSize: "38 x 28 x 24 cm folded",
    unitsPerCarton: "24 units",
    cartonWeight: "12.4 kg",
    koreanMarketFit:
      "Neutral home storage fits small-space living, baby rooms, and lifestyle home channels.",
    suggestedSalesChannels: ["Naver Smart Store", "Department stores", "Specialty retail stores"],
    riskNotes,
    imagePlaceholder: imageByCategory["Home Goods"],
  },
  {
    id: "adaptogen-cacao-mix",
    name: "Adaptogen Cacao Mix",
    category: "Health & Wellness",
    sellerId: "cleanline-labs",
    sellerName: "CleanLine Labs",
    sellerLocation: "Boston, Massachusetts",
    shortDescription: "Functional cacao powder with reishi, maca, and cinnamon.",
    longDescription:
      "Warm beverage mix for wellness cafes, gift sets, and premium online grocery with batch COA support.",
    wholesalePrice: "$6.20 / pouch",
    wholesalePriceValue: 6.2,
    moq: "1,200 pouches",
    moqUnits: 1200,
    leadTime: "30-38 days",
    monthlyCapacity: "80,000 pouches",
    sampleAvailable: true,
    privateLabelAvailable: true,
    countryOfOrigin: "United States",
    shippingOrigin: "Boston, MA",
    incoterms: ["EXW", "FOB", "CIF"],
    hsCode: "1806.90",
    certifications: ["GMP", "FDA Registered"],
    documentsAvailable: [...commonDocuments, "COA", "FDA registration"],
    shelfLife: "18 months",
    packageSize: "240 g pouch",
    unitsPerCarton: "24 pouches",
    cartonWeight: "8 kg",
    koreanMarketFit:
      "Cafe-friendly functional beverages create discovery moments for wellness-minded consumers.",
    suggestedSalesChannels: ["Cafes", "Naver Smart Store", "Department stores"],
    riskNotes,
    imagePlaceholder: imageByCategory["Health & Wellness"],
  },
  {
    id: "mineral-sunscreen-stick",
    name: "Mineral Sunscreen Stick",
    category: "Beauty & Skincare",
    sellerId: "pacific-naturals",
    sellerName: "Pacific Naturals Co.",
    sellerLocation: "Los Angeles, California",
    shortDescription: "Travel-friendly zinc oxide sunscreen stick for face and body.",
    longDescription:
      "Portable mineral sunscreen format with family and outdoor positioning for seasonal programs.",
    wholesalePrice: "$3.55 / stick",
    wholesalePriceValue: 3.55,
    moq: "3,000 sticks",
    moqUnits: 3000,
    leadTime: "30-38 days",
    monthlyCapacity: "140,000 sticks",
    sampleAvailable: true,
    privateLabelAvailable: true,
    countryOfOrigin: "United States",
    shippingOrigin: "Los Angeles, CA",
    incoterms: ["EXW", "FOB", "CIF", "DDP"],
    hsCode: "3304.99",
    certifications: ["GMP", "Leaping Bunny"],
    documentsAvailable: [...commonDocuments, "COA", "MSDS"],
    shelfLife: "30 months",
    packageSize: "18 g twist-up stick",
    unitsPerCarton: "144 sticks",
    cartonWeight: "9.7 kg",
    koreanMarketFit:
      "Portable sun care is highly relevant for Korean beauty shoppers, though SPF claims require careful local review.",
    suggestedSalesChannels: ["Olive Young", "Coupang", "Specialty retail stores"],
    riskNotes,
    imagePlaceholder: imageByCategory["Beauty & Skincare"],
  },
  {
    id: "freeze-dried-berry-blend",
    name: "Freeze-Dried Berry Blend",
    category: "Food & Beverage",
    sellerId: "frontier-gourmet",
    sellerName: "Frontier Gourmet Group",
    sellerLocation: "Chicago, Illinois",
    shortDescription: "Shelf-stable strawberry, blueberry, and raspberry snack mix.",
    longDescription:
      "Lightweight fruit snack for kids, cafes, and cereal toppings with strong shelf life and clean label.",
    wholesalePrice: "$1.95 / pouch",
    wholesalePriceValue: 1.95,
    moq: "8,000 pouches",
    moqUnits: 8000,
    leadTime: "20-26 days",
    monthlyCapacity: "350,000 pouches",
    sampleAvailable: true,
    privateLabelAvailable: true,
    countryOfOrigin: "United States",
    shippingOrigin: "Chicago, IL",
    incoterms: ["FOB", "CIF"],
    hsCode: "0813.40",
    certifications: ["FDA Registered", "SQF"],
    documentsAvailable: [...commonDocuments, "COA", "FDA registration"],
    shelfLife: "18 months",
    packageSize: "25 g pouch",
    unitsPerCarton: "120 pouches",
    cartonWeight: "5.3 kg",
    koreanMarketFit:
      "Clean fruit snacks fit kids, cafe toppings, and premium pantry discovery channels.",
    suggestedSalesChannels: ["Coupang", "Cafes", "Department stores"],
    riskNotes,
    imagePlaceholder: imageByCategory["Food & Beverage"],
  },
  {
    id: "weighted-eye-pillow",
    name: "Weighted Lavender Eye Pillow",
    category: "Health & Wellness",
    sellerId: "blue-ridge-wellness",
    sellerName: "Blue Ridge Wellness",
    sellerLocation: "Asheville, North Carolina",
    shortDescription: "Cotton eye pillow filled with flaxseed and dried lavender.",
    longDescription:
      "Spa and home relaxation accessory for wellness boutiques, yoga studios, and gift programs.",
    wholesalePrice: "$4.40 / unit",
    wholesalePriceValue: 4.4,
    moq: "900 units",
    moqUnits: 900,
    leadTime: "24-32 days",
    monthlyCapacity: "35,000 units",
    sampleAvailable: true,
    privateLabelAvailable: true,
    countryOfOrigin: "United States",
    shippingOrigin: "Charlotte, NC",
    incoterms: ["EXW", "FOB"],
    hsCode: "6307.90",
    certifications: ["USDA Organic"],
    documentsAvailable: [...commonDocuments, "Material declaration", "Organic certificate"],
    shelfLife: "36 months",
    packageSize: "22 x 10 cm cotton pouch",
    unitsPerCarton: "80 units",
    cartonWeight: "13.2 kg",
    koreanMarketFit:
      "Relaxation and self-care accessories pair well with spa, yoga, and gift retail programs.",
    suggestedSalesChannels: ["Specialty retail stores", "Naver Smart Store", "Gyms"],
    riskNotes,
    imagePlaceholder: imageByCategory["Health & Wellness"],
  },
  {
    id: "performance-running-socks",
    name: "Performance Running Socks",
    category: "Apparel",
    sellerId: "nova-active",
    sellerName: "Nova Active Supply",
    sellerLocation: "Miami, Florida",
    shortDescription: "Cushioned moisture-wicking socks with recycled nylon.",
    longDescription:
      "Athletic sock program for running, hiking, and gym retail with hang-tag customization.",
    wholesalePrice: "$2.10 / pair",
    wholesalePriceValue: 2.1,
    moq: "3,000 pairs",
    moqUnits: 3000,
    leadTime: "28-36 days",
    monthlyCapacity: "180,000 pairs",
    sampleAvailable: true,
    privateLabelAvailable: true,
    countryOfOrigin: "United States",
    shippingOrigin: "Miami, FL",
    incoterms: ["EXW", "FOB", "CIF"],
    hsCode: "6115.95",
    certifications: ["OEKO-TEX", "GRS"],
    documentsAvailable: [...commonDocuments, "Fabric test reports"],
    packageSize: "Single pair hang tag",
    unitsPerCarton: "200 pairs",
    cartonWeight: "10.8 kg",
    koreanMarketFit:
      "Running and hiking communities create demand for premium socks with technical claims.",
    suggestedSalesChannels: ["Gyms", "Naver Smart Store", "Specialty retail stores"],
    riskNotes,
    imagePlaceholder: imageByCategory["Apparel"],
  },
];

const usMarketFitByCategory: Record<ProductCategory, string> = {
  "Beauty & Skincare":
    "K-beauty products have strong U.S. demand when positioned around innovation, gentle formulas, and trend-led retail storytelling.",
  "Food & Beverage":
    "Korean food and beverage products fit U.S. specialty grocery, Asian retail, ecommerce bundles, and mainstream discovery channels.",
  Apparel:
    "Korean apparel suppliers can serve U.S. boutiques and online brands looking for fast trend cycles, quality basics, and private label programs.",
  Supplements:
    "Korean wellness formats can appeal to U.S. buyers when documentation, claims review, and ingredient transparency are clear.",
  "Home Goods":
    "Korean home and lifestyle goods fit U.S. buyers seeking compact-living design, clean packaging, and differentiated imported assortments.",
  "Pet Products":
    "Korean pet care products can work for U.S. specialty retailers when ingredient statements, labeling, and safety documentation are ready.",
  "Health & Wellness":
    "Korean wellness products fit U.S. ecommerce, spa, boutique retail, and gift channels when positioned with clear documentation.",
};

const usSalesChannelsByCategory: Record<ProductCategory, string[]> = {
  "Beauty & Skincare": ["Amazon", "Target", "Sephora", "Specialty beauty retail"],
  "Food & Beverage": ["Amazon", "Asian grocery chains", "Specialty grocery", "Wholesale clubs"],
  Apparel: ["Boutiques", "Shopify stores", "Department stores", "Online marketplaces"],
  Supplements: ["Amazon", "Wellness retailers", "Gyms", "DTC subscriptions"],
  "Home Goods": ["Wayfair", "Boutiques", "Department stores", "Amazon"],
  "Pet Products": ["Petco", "Chewy", "Pet specialty retail", "Amazon"],
  "Health & Wellness": ["Wellness retailers", "Spas", "Amazon", "Boutiques"],
};

export const products: Product[] = baseProducts.map((product) => {
  const seller = sellers.find((item) => item.id === product.sellerId);

  return {
    ...product,
    sellerName: seller?.name ?? product.sellerName,
    sellerLocation: seller?.location ?? product.sellerLocation,
    sellerLogoUrl: seller?.logoUrl,
    sellerUseDefaultLogo: seller?.useDefaultLogo ?? true,
    countryOfOrigin: "South Korea",
    shippingOrigin: seller?.location ?? "South Korea",
    koreanMarketFit: usMarketFitByCategory[product.category],
    suggestedSalesChannels: usSalesChannelsByCategory[product.category],
    riskNotes: [
      "U.S. buyer should verify import, FDA, FTC, labeling, and state-level requirements before purchase.",
      "Regulatory requirements vary by category and sales channel.",
    ],
    verificationStatus: "verified",
  };
});

const baseBuyers: Buyer[] = [
  {
    id: "hanseong-trade",
    name: "Hanseong Trade Partners",
    location: "Seoul, South Korea",
    buyerType: "Importer",
    interestedCategories: ["Food & Beverage", "Supplements"],
    targetOrderSize: "$25,000-$60,000 per order",
    annualImportVolume: "$2.4M",
    salesChannels: ["Coupang", "Naver Smart Store", "Department stores"],
    importExperience: "8 years importing shelf-stable foods and wellness products from the U.S. and Japan.",
    requiredDocuments: [...commonDocuments, "FDA registration", "COA"],
    preferredPaymentTerms: ["Letter of credit", "30% deposit / 70% before shipment"],
    timeline: "Ready to order within 45 days",
    marketStrategy:
      "Build a premium U.S. snack and wellness assortment for online launch before expanding to offline retail.",
    contactPerson: "Jiwon Park",
    contactEmail: "sourcing@hanseongtrade.example",
    verified: true,
  },
  {
    id: "olivewave-retail",
    name: "OliveWave Retail Group",
    location: "Seoul, South Korea",
    buyerType: "Retailer",
    interestedCategories: ["Beauty & Skincare", "Health & Wellness"],
    targetOrderSize: "$15,000-$40,000 per SKU",
    annualImportVolume: "$1.8M",
    salesChannels: ["Olive Young", "Specialty retail stores", "Naver Smart Store"],
    importExperience: "5 years sourcing clean beauty, indie skincare, and wellness accessories.",
    requiredDocuments: [...commonDocuments, "COA", "MSDS"],
    preferredPaymentTerms: ["Wire transfer", "Escrow available"],
    timeline: "Sampling now, purchase order in 60-90 days",
    marketStrategy:
      "Introduce ingredient-led U.S. indie beauty brands through curated retail drops and influencer kits.",
    contactPerson: "Minseo Choi",
    contactEmail: "buying@olivewave.example",
    verified: true,
  },
  {
    id: "busan-pet-link",
    name: "Busan Pet Link",
    location: "Busan, South Korea",
    buyerType: "Distributor",
    interestedCategories: ["Pet Products"],
    targetOrderSize: "$10,000-$35,000 per order",
    annualImportVolume: "$950K",
    salesChannels: ["Pet specialty retail", "Offline wholesale", "Coupang"],
    importExperience: "6 years distributing premium pet food, grooming, and accessories.",
    requiredDocuments: [...commonDocuments, "COA", "Health certificate", "Ingredient statement"],
    preferredPaymentTerms: ["Letter of credit", "Wire transfer"],
    timeline: "Evaluating suppliers for Q3 launch",
    marketStrategy:
      "Expand U.S. premium pet treat and grooming portfolio for vet-adjacent specialty retailers.",
    contactPerson: "Daehyun Lim",
    contactEmail: "partners@busanpetlink.example",
    verified: true,
  },
  {
    id: "noryang-commerce",
    name: "Noryang Commerce",
    location: "Incheon, South Korea",
    buyerType: "Online Seller",
    interestedCategories: ["Home Goods", "Apparel", "Health & Wellness"],
    targetOrderSize: "$5,000-$18,000 trial orders",
    annualImportVolume: "$620K",
    salesChannels: ["Coupang", "Naver Smart Store"],
    importExperience: "3 years testing imported lifestyle products through online marketplaces.",
    requiredDocuments: [...commonDocuments, "Material declaration"],
    preferredPaymentTerms: ["Credit card for samples", "Wire transfer"],
    timeline: "Trial orders within 30 days",
    marketStrategy:
      "Validate imported lifestyle products with fast online tests before committing to larger seasonal buys.",
    contactPerson: "Sora Jeong",
    contactEmail: "hello@noryangcommerce.example",
    verified: false,
  },
  {
    id: "lotte-style-buying",
    name: "Lotte Style Buying Office",
    location: "Seoul, South Korea",
    buyerType: "Department Store Buyer",
    interestedCategories: ["Beauty & Skincare", "Home Goods", "Food & Beverage"],
    targetOrderSize: "$50,000-$150,000 seasonal programs",
    annualImportVolume: "$8.6M",
    salesChannels: ["Department stores", "Specialty retail stores"],
    importExperience: "12 years coordinating department store launches and seasonal imported gift programs.",
    requiredDocuments: [...commonDocuments, "COA", "MSDS", "Safety test reports"],
    preferredPaymentTerms: ["Letter of credit", "Net 30 for approved suppliers"],
    timeline: "Reviewing vendors for next seasonal buying cycle",
    marketStrategy:
      "Source premium American brands for high-trust in-store merchandising and holiday gift assortments.",
    contactPerson: "Hyunwoo Kang",
    contactEmail: "globalbuying@lottestyle.example",
    verified: true,
  },
  {
    id: "jeju-wellness-import",
    name: "Jeju Wellness Import Co.",
    location: "Jeju, South Korea",
    buyerType: "Importer",
    interestedCategories: ["Health & Wellness", "Beauty & Skincare"],
    targetOrderSize: "$12,000-$30,000 per order",
    annualImportVolume: "$780K",
    salesChannels: ["Specialty retail stores", "Naver Smart Store", "Offline wholesale"],
    importExperience: "4 years importing spa, aromatherapy, and natural personal care products.",
    requiredDocuments: [...commonDocuments, "COA", "Organic certificate"],
    preferredPaymentTerms: ["Wire transfer", "30% deposit / 70% before shipment"],
    timeline: "Samples needed within 2 weeks",
    marketStrategy:
      "Curate wellness products for resort retail, spas, and premium online gift sets.",
    contactPerson: "Yuna Seo",
    contactEmail: "sourcing@jejuwellness.example",
    verified: true,
  },
  {
    id: "daegu-active-lab",
    name: "Daegu Active Lab",
    location: "Daegu, South Korea",
    buyerType: "Distributor",
    interestedCategories: ["Apparel", "Health & Wellness", "Supplements"],
    targetOrderSize: "$20,000-$75,000 per order",
    annualImportVolume: "$1.3M",
    salesChannels: ["Gyms", "Coupang", "Naver Smart Store"],
    importExperience: "7 years importing active lifestyle products for fitness retailers.",
    requiredDocuments: [...commonDocuments, "Fabric test reports", "COA"],
    preferredPaymentTerms: ["Letter of credit", "Wire transfer"],
    timeline: "Planning Q4 active lifestyle assortment",
    marketStrategy:
      "Bundle U.S. activewear, hydration, and wellness products for fitness communities.",
    contactPerson: "Taeho Kim",
    contactEmail: "buying@daeguactivelab.example",
    verified: true,
  },
  {
    id: "myeongdong-beauty-hub",
    name: "Myeongdong Beauty Hub",
    location: "Seoul, South Korea",
    buyerType: "Retailer",
    interestedCategories: ["Beauty & Skincare"],
    targetOrderSize: "$8,000-$25,000 launch orders",
    annualImportVolume: "$1.1M",
    salesChannels: ["Specialty retail stores", "Olive Young", "Naver Smart Store"],
    importExperience: "6 years launching imported skincare through tourist and local retail channels.",
    requiredDocuments: [...commonDocuments, "COA", "MSDS"],
    preferredPaymentTerms: ["Wire transfer", "Escrow available"],
    timeline: "Open to immediate sampling",
    marketStrategy:
      "Find differentiated U.S. clean beauty products that complement Korean skincare routines.",
    contactPerson: "Harin Moon",
    contactEmail: "imports@myeongdongbeauty.example",
    verified: true,
  },
  {
    id: "gangnam-family-mart",
    name: "Gangnam Family Mart Online",
    location: "Seoul, South Korea",
    buyerType: "Online Seller",
    interestedCategories: ["Home Goods", "Pet Products", "Food & Beverage"],
    targetOrderSize: "$6,000-$20,000 trial orders",
    annualImportVolume: "$540K",
    salesChannels: ["Coupang", "Naver Smart Store"],
    importExperience: "2 years importing small-batch products for family-focused online stores.",
    requiredDocuments: [...commonDocuments, "Ingredient statement", "Safety test reports"],
    preferredPaymentTerms: ["Credit card for samples", "Wire transfer"],
    timeline: "Trial sourcing this month",
    marketStrategy:
      "Test useful family, pet, and pantry products with paid search and marketplace bundles.",
    contactPerson: "Eunbi Han",
    contactEmail: "source@gfamilymart.example",
    verified: false,
  },
  {
    id: "korealine-distribution",
    name: "KoreaLine Distribution",
    location: "Incheon, South Korea",
    buyerType: "Distributor",
    interestedCategories: ["Food & Beverage", "Home Goods", "Pet Products"],
    targetOrderSize: "$35,000-$100,000 container programs",
    annualImportVolume: "$4.2M",
    salesChannels: ["Offline wholesale", "Department stores", "Coupang"],
    importExperience: "10 years managing customs, warehousing, and national wholesale distribution.",
    requiredDocuments: [...commonDocuments, "COA", "Health certificate", "Material declaration"],
    preferredPaymentTerms: ["Letter of credit", "Net 30 for approved suppliers"],
    timeline: "Seeking suppliers for annual distribution agreements",
    marketStrategy:
      "Build exclusive distribution relationships with export-ready American brands across multiple categories.",
    contactPerson: "Jongmin Yoo",
    contactEmail: "partnerships@korealine.example",
    verified: true,
  },
];

const americanBuyerProfiles: Array<Pick<
  Buyer,
  | "id"
  | "name"
  | "location"
  | "buyerType"
  | "annualImportVolume"
  | "salesChannels"
  | "importExperience"
  | "requiredDocuments"
  | "preferredPaymentTerms"
  | "marketStrategy"
  | "contactPerson"
  | "contactEmail"
  | "verified"
>> = [
  {
    id: "hanseong-trade",
    name: "Pacific Coast Import Partners",
    location: "Los Angeles, California",
    buyerType: "Importer",
    annualImportVolume: "$3.1M",
    salesChannels: ["Amazon", "Specialty grocery", "Asian grocery chains"],
    importExperience: "9 years importing Korean food, beauty, and wellness products for U.S. retail channels.",
    requiredDocuments: [...commonDocuments, "FDA facility registration", "COA", "English label files"],
    preferredPaymentTerms: ["Letter of credit", "30% deposit / 70% before shipment"],
    marketStrategy:
      "Build a premium Korean food and wellness assortment for West Coast specialty retail before expanding nationally.",
    contactPerson: "Emily Carter",
    contactEmail: "sourcing@pacificcoastimport.example",
    verified: true,
  },
  {
    id: "olivewave-retail",
    name: "GlowBridge Retail Group",
    location: "New York, New York",
    buyerType: "Retailer",
    annualImportVolume: "$2.2M",
    salesChannels: ["Specialty beauty retail", "Amazon", "Shopify stores"],
    importExperience: "6 years sourcing K-beauty skincare, indie cosmetics, and wellness accessories.",
    requiredDocuments: [...commonDocuments, "COA", "MSDS", "INCI ingredient list"],
    preferredPaymentTerms: ["Wire transfer", "Escrow available"],
    marketStrategy:
      "Launch differentiated Korean beauty brands through curated online drops and U.S. influencer seeding.",
    contactPerson: "Rachel Morgan",
    contactEmail: "buying@glowbridge.example",
    verified: true,
  },
  {
    id: "busan-pet-link",
    name: "Northstar Pet Distribution",
    location: "Chicago, Illinois",
    buyerType: "Distributor",
    annualImportVolume: "$1.4M",
    salesChannels: ["Pet specialty retail", "Chewy", "Regional wholesale"],
    importExperience: "7 years distributing imported premium pet treats, grooming, and accessories.",
    requiredDocuments: [...commonDocuments, "COA", "Ingredient statement", "U.S. label review"],
    preferredPaymentTerms: ["Letter of credit", "Wire transfer"],
    marketStrategy:
      "Expand Korean premium pet care products across Midwest specialty pet retailers and ecommerce.",
    contactPerson: "Michael Adams",
    contactEmail: "partners@northstarpet.example",
    verified: true,
  },
  {
    id: "noryang-commerce",
    name: "Hudson Market Online",
    location: "Jersey City, New Jersey",
    buyerType: "Online Seller",
    annualImportVolume: "$720K",
    salesChannels: ["Amazon", "Shopify stores", "TikTok Shop"],
    importExperience: "4 years testing imported lifestyle products through U.S. online marketplaces.",
    requiredDocuments: [...commonDocuments, "Material declaration", "English packaging files"],
    preferredPaymentTerms: ["Credit card for samples", "Wire transfer"],
    marketStrategy:
      "Validate Korean lifestyle products with fast online tests before committing to larger seasonal buys.",
    contactPerson: "Daniel Lee",
    contactEmail: "hello@hudsonmarketonline.example",
    verified: false,
  },
  {
    id: "lotte-style-buying",
    name: "Meridian Department Stores",
    location: "Seattle, Washington",
    buyerType: "Department Store Buyer",
    annualImportVolume: "$9.2M",
    salesChannels: ["Department stores", "Specialty retail stores"],
    importExperience: "13 years coordinating imported brand launches and seasonal gift programs in the U.S.",
    requiredDocuments: [...commonDocuments, "COA", "MSDS", "Safety test reports"],
    preferredPaymentTerms: ["Letter of credit", "Net 30 for approved suppliers"],
    marketStrategy:
      "Source premium Korean brands for high-trust in-store merchandising and seasonal gift assortments.",
    contactPerson: "Amanda Wilson",
    contactEmail: "globalbuying@meridiandepartment.example",
    verified: true,
  },
  {
    id: "jeju-wellness-import",
    name: "Desert Bloom Wellness",
    location: "Phoenix, Arizona",
    buyerType: "Importer",
    annualImportVolume: "$880K",
    salesChannels: ["Spas", "Wellness retailers", "Shopify stores"],
    importExperience: "5 years importing spa, aromatherapy, and natural personal care products.",
    requiredDocuments: [...commonDocuments, "COA", "Organic certificate"],
    preferredPaymentTerms: ["Wire transfer", "30% deposit / 70% before shipment"],
    marketStrategy:
      "Curate Korean wellness products for spas, resort retail, and premium online gift sets.",
    contactPerson: "Lauren Brooks",
    contactEmail: "sourcing@desertbloomwellness.example",
    verified: true,
  },
  {
    id: "daegu-active-lab",
    name: "Summit Active Imports",
    location: "Denver, Colorado",
    buyerType: "Distributor",
    annualImportVolume: "$1.6M",
    salesChannels: ["Gyms", "Boutiques", "Amazon"],
    importExperience: "8 years importing active lifestyle products for fitness retailers.",
    requiredDocuments: [...commonDocuments, "Fabric test reports", "COA"],
    preferredPaymentTerms: ["Letter of credit", "Wire transfer"],
    marketStrategy:
      "Bundle Korean activewear, hydration, and wellness products for U.S. fitness communities.",
    contactPerson: "Chris Bennett",
    contactEmail: "buying@summitactiveimports.example",
    verified: true,
  },
  {
    id: "myeongdong-beauty-hub",
    name: "SoHo Beauty Collective",
    location: "New York, New York",
    buyerType: "Retailer",
    annualImportVolume: "$1.5M",
    salesChannels: ["Specialty beauty retail", "Amazon", "Shopify stores"],
    importExperience: "7 years launching imported skincare through U.S. beauty retail channels.",
    requiredDocuments: [...commonDocuments, "COA", "MSDS", "INCI ingredient list"],
    preferredPaymentTerms: ["Wire transfer", "Escrow available"],
    marketStrategy:
      "Find differentiated K-beauty products that complement U.S. skincare routines and creator-led discovery.",
    contactPerson: "Olivia Parker",
    contactEmail: "imports@sohobeautycollective.example",
    verified: true,
  },
  {
    id: "gangnam-family-mart",
    name: "Family Goods Direct",
    location: "Austin, Texas",
    buyerType: "Online Seller",
    annualImportVolume: "$640K",
    salesChannels: ["Amazon", "Shopify stores", "TikTok Shop"],
    importExperience: "3 years importing small-batch products for family-focused U.S. online stores.",
    requiredDocuments: [...commonDocuments, "Ingredient statement", "Safety test reports"],
    preferredPaymentTerms: ["Credit card for samples", "Wire transfer"],
    marketStrategy:
      "Test useful Korean family, pet, and pantry products with paid search and marketplace bundles.",
    contactPerson: "Megan Hughes",
    contactEmail: "source@familygoodsdirect.example",
    verified: false,
  },
  {
    id: "korealine-distribution",
    name: "Atlantic Trade Distribution",
    location: "Atlanta, Georgia",
    buyerType: "Distributor",
    annualImportVolume: "$4.8M",
    salesChannels: ["Regional wholesale", "Department stores", "Amazon"],
    importExperience: "11 years managing customs, warehousing, and national wholesale distribution in the U.S.",
    requiredDocuments: [...commonDocuments, "COA", "Ingredient statement", "Material declaration"],
    preferredPaymentTerms: ["Letter of credit", "Net 30 for approved suppliers"],
    marketStrategy:
      "Build exclusive distribution relationships with export-ready Korean brands across multiple categories.",
    contactPerson: "Jonathan Reed",
    contactEmail: "partnerships@atlantictradedistribution.example",
    verified: true,
  },
];

export const buyers: Buyer[] = baseBuyers.map((buyer) => ({
  ...buyer,
  ...americanBuyerProfiles.find((profile) => profile.id === buyer.id),
  useDefaultLogo: true,
  verificationStatus: "verified",
}));

export const publicSellers = sellers.filter(
  (seller) => seller.verificationStatus === "verified",
);

export const publicProducts = products.filter((product) => {
  const seller = sellers.find((item) => item.id === product.sellerId);
  return (
    product.verificationStatus === "verified" &&
    seller?.verificationStatus === "verified"
  );
});

export const publicBuyers = buyers.filter(
  (buyer) => buyer.verificationStatus === "verified",
);

export function getProduct(id: string) {
  return publicProducts.find((product) => product.id === id);
}

export function getSeller(id: string) {
  return publicSellers.find((seller) => seller.id === id);
}

export function getBuyer(id: string) {
  const numericId = Number(id);

  if (Number.isInteger(numericId) && numericId >= 1 && numericId <= buyers.length) {
    return buyers[numericId - 1];
  }

  return publicBuyers.find((buyer) => buyer.id === id);
}

export function getProductsBySeller(sellerId: string) {
  return publicProducts.filter((product) => product.sellerId === sellerId);
}

export function getSellerProductCount(sellerId: string) {
  return products.filter((product) => product.sellerId === sellerId).length;
}
