ALTER TABLE "Company"
ADD COLUMN "displayNameEn" TEXT NOT NULL DEFAULT '',
ADD COLUMN "descriptionEn" TEXT NOT NULL DEFAULT '';

ALTER TABLE "SellerProfile"
ADD COLUMN "exportExperienceEn" TEXT NOT NULL DEFAULT '';

ALTER TABLE "Product"
ADD COLUMN "nameEn" TEXT NOT NULL DEFAULT '',
ADD COLUMN "tagsEn" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "shortDescriptionEn" TEXT NOT NULL DEFAULT '',
ADD COLUMN "detailedDescriptionEn" TEXT NOT NULL DEFAULT '',
ADD COLUMN "buyerNotesEn" TEXT NOT NULL DEFAULT '';
