"use client";

import { Check, Loader2, X } from "lucide-react";
import { useEffect, useState } from "react";

type Profile = { id: string; companyId: string; country: string; bankName: string; accountHolder: string; accountNumberMasked: string | null; status: string; updatedAt: string; company: { legalName: string; tradeName: string | null } };
export function AdminPayoutProfileManagement() {
  const [profiles, setProfiles] = useState<Profile[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  async function load() { setLoading(true); try { const response = await fetch("/api/admin/payout-profiles", { cache: "no-store" }); const data = await response.json().catch(() => null); if (!response.ok) throw new Error(data?.error ?? "Unable to load payout profiles."); setProfiles(data.profiles ?? []); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load payout profiles."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []); async function action(id: string, action: string) { setError(""); try { const response = await fetch(`/api/admin/payout-profiles/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action }) }); const data = await response.json().catch(() => null); if (!response.ok) throw new Error(data?.error ?? "Unable to update payout profile."); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to update payout profile."); } }
  return <section className="grid gap-4">{error ? <p className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p> : null}{loading ? <Loader2 className="size-5 animate-spin" /> : <div className="overflow-x-auto rounded-xl border"><table className="min-w-[800px] text-left text-sm"><thead className="border-b theme-surface-muted"><tr>{["Seller", "Country", "Bank", "Account holder", "Masked account", "Status", "Updated", ""].map((label) => <th key={label} className="px-3 py-3 font-semibold">{label}</th>)}</tr></thead><tbody>{profiles.map((profile) => <tr key={profile.id} className="border-b theme-border"><td className="px-3 py-3 font-medium">{profile.company.tradeName || profile.company.legalName}</td><td className="px-3 py-3">{profile.country}</td><td className="px-3 py-3">{profile.bankName}</td><td className="px-3 py-3">{profile.accountHolder}</td><td className="px-3 py-3">{profile.accountNumberMasked ?? "—"}</td><td className="px-3 py-3">{profile.status}</td><td className="px-3 py-3">{new Date(profile.updatedAt).toLocaleDateString()}</td><td className="px-3 py-3"><div className="flex gap-2"><button onClick={() => void action(profile.id, "verify")} className="inline-flex size-8 items-center justify-center rounded border text-emerald-700" aria-label="Verify payout profile"><Check className="size-4" /></button><button onClick={() => void action(profile.id, "reject")} className="inline-flex size-8 items-center justify-center rounded border text-red-700" aria-label="Reject payout profile"><X className="size-4" /></button></div></td></tr>)}</tbody></table></div>}</section>;
}
